### ISSUE TITLE
Conflict with Firma: Civilization.

### ISSUE THREAD

**Issue by Sigmenzzz** [uTa4u/TFC-Woodworking#3]
The canoe in Firma: Civilization couldn't be made , because the horizontal stripped log couldn't be deal with saw.

**Comment by Quizer9O8** [comment]
I'd like to add more context upon this issue. Due to the way TFC Woodworking interacts with logs, wood and planks you're not able to make Canoes (Canoe Components) with your saw and axe you're normally able to do in [Firma: Civilization (TFC)](https://www.curseforge.com/minecraft/mc-mods/firmaciv). You need the saw to remove the top part of the log and dig it out after using an axe.
![image](https://github.com/user-attachments/assets/8506daaa-5838-4f7f-a62a-7fa9c5b490b8)
![image](https://github.com/user-attachments/assets/8b6c17fc-9835-4933-9fb8-b5e46e6bf73f)
